language: python
python:
  - "2.7"
addons:
    apt:
        packages:
            - python-dev
services:
  - redis-server
          
install:
  - pip install -r requirements.txt
script: python rmc_test_ui.py
                                                                                                                             
                             
